# Generated by Django 4.2.9 on 2026-05-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Alert Message')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='Severity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Triggered At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
