# Generated by Django 4.2.9 on 2026-05-06 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Client Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('webhook_url', models.URLField(blank=True, help_text='URL to send billing alerts to their system', null=True, verbose_name='System Webhook URL')),
                ('webhook_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Webhook Auth Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Standard Hosting', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Price')),
                ('cutoff_day', models.IntegerField(default=1, verbose_name='Cutoff Day (1-31)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('last_paid_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing.client')),
            ],
        ),
    ]
