# Generated by Django 4.2.9 on 2026-05-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_client_api_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='webhook_token',
        ),
        migrations.RemoveField(
            model_name='client',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Física'),
        ),
        migrations.AddField(
            model_name='client',
            name='cedula_ruc',
            field=models.CharField(default='0000000000', max_length=20, unique=True, verbose_name='Cédula / RUC'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Razón Social / Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
