# Generated by Django 4.2.9 on 2026-05-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_client_webhook_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vps_monthly_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Mensual del VPS ($)')),
            ],
            options={
                'verbose_name': 'ConfiguraciÃ³n del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
