# Generated by Django 4.2.9 on 2026-05-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='total_server_ram_gb',
            field=models.FloatField(default=1.0, verbose_name='Memoria RAM Total del VPS (GB)'),
        ),
    ]
