# Generated by Django 4.2.9 on 2026-05-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100, unique=True, verbose_name='Container ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('running', 'Running'), ('exited', 'Exited'), ('paused', 'Paused'), ('created', 'Created')], default='created', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'ordering': ['-created_at'],
            },
        ),
    ]
