# Generated by Django 4.2.9 on 2026-05-06 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '__first__'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='ContainerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('ram_mb', models.FloatField(default=0.0)),
                ('ram_percent', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.container')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['container', '-timestamp'], name='monitoring__contain_b78c75_idx')],
            },
        ),
    ]
