# Generated by Django 4.2.9 on 2026-05-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_container_subscription_containermetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Name'),
        ),
    ]
