# Generated by Django 4.2.9 on 2026-05-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_container_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyContainerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_cpu_percent', models.FloatField()),
                ('avg_ram_mb', models.FloatField()),
                ('total_gb_hours', models.FloatField(help_text='Cumulative GB-Hours for the month')),
                ('timestamp', models.DateTimeField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_metrics', to='monitoring.container')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('container', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='HourlyContainerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_cpu_percent', models.FloatField()),
                ('avg_ram_mb', models.FloatField()),
                ('max_cpu_percent', models.FloatField()),
                ('max_ram_mb', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_metrics', to='monitoring.container')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('container', 'timestamp')},
            },
        ),
    ]
